// <auto-generated />
using System;
using Congratulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Congratulator.Migrations
{
    [DbContext(typeof(BirthdayDbContext))]
    partial class BirthdayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Congratulator.Models.BirthdayRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BirthdayRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1993, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Constantine",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1994, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(1994, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alex",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(1992, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(1993, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(1996, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jack",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(1987, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sam",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(1990, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nataniel",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(1996, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kim",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(1991, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xavier",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(1994, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anna",
                            pictureUrl = ""
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(1993, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denis",
                            pictureUrl = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
